[package]
name = "ngrok"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "The ngrok agent SDK"
repository = "https://github.com/ngrok/ngrok-rs"

[dependencies]
prost = "0.11.3"
muxado = { path = "../muxado", version = "0.1.0" }
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
thiserror = "1.0.37"
base64 = "0.13.1"
tokio = { version = "1.23.0", features = ["sync", "time"] }
tracing = "0.1.37"
async-rustls = { version = "0.3.0" }
tokio-util = { version = "0.7.4", features = ["compat"] }
futures = "0.3.25"
hyper = { version = "0.14.23", features = ["server"] }
axum = { version = "0.6.1", features = ["tokio"] }
rustls-pemfile = "1.0.1"

[build-dependencies]
prost-build = "0.11.3"

[dev-dependencies]
anyhow = "1.0.66"
axum = "0.6.1"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
