/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function session(): Promise<JsSession>
export type JsSession = Session
export class Session {
  constructor()
  hi(): Promise<string>
  startTunnel(): Promise<JsTunnel>
}
export type JsTunnel = Tunnel
export class Tunnel {
  constructor()
  getId(): string
  getUrl(): string
  forwardHttp(addr: string): Promise<void>
}
