/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type JsSessionBuilder = SessionBuilder
export class SessionBuilder {
  constructor()
  authtokenFromEnv(): this
  metadata(metadata: string): this
  connect(): Promise<JsSession>
}
export type JsSession = Session
export class Session {
  constructor()
  tcpEndpoint(): JsTcpEndpoint
}
export type JsTcpEndpoint = TcpEndpoint
export class TcpEndpoint {
  constructor()
  metadata(metadata: string): this
  remoteAddr(remoteAddr: string): this
  listen(): Promise<JsTunnel>
}
export type JsTunnel = Tunnel
export class Tunnel {
  constructor()
  getId(): string
  getUrl(): string
  forwardTcp(addr: string): Promise<void>
  forwardUnix(addr: string): Promise<void>
}
