on: [push]

name: Build and Test

jobs:
  build_and_test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install protoc
        run: sudo apt-get install -y protobuf-compiler
      - uses: actions-rs/cargo@v1
        name: build crate
        with:
          command: build
          args: --release --all-features
      - uses: actions-rs/cargo@v1
        name: build examples
        with:
          command: build
          args: --release --all-features --examples
      - uses: actions-rs/cargo@v1
        name: test crate
        with:
          command: test
          args: --release --all-features
