on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Continuous integration

jobs:
  udeps:
    name: Udeps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
      - run: alias curl="curl --retry 5 --retry-all-errors"
      - run: curl https://direnv.net/install.sh | bash
      - run: direnv allow
      - run: direnv export gha >> "$GITHUB_ENV"
      - uses: actions-rs/cargo@v1
        with:
          command: udeps
          args: --workspace --all-targets --all-features

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
      - run: alias curl="curl --retry 5 --retry-all-errors"
      - run: curl https://direnv.net/install.sh | bash
      - run: direnv allow
      - run: direnv export gha >> "$GITHUB_ENV"
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
      - run: alias curl="curl --retry 5 --retry-all-errors"
      - run: curl https://direnv.net/install.sh | bash
      - run: direnv allow
      - run: direnv export gha >> "$GITHUB_ENV"
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features --workspace -- -D warnings

  test-nix:
    name: Test Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
      - run: alias curl="curl --retry 5 --retry-all-errors"
      - run: curl https://direnv.net/install.sh | bash
      - run: direnv allow
      - run: direnv export gha >> "$GITHUB_ENV"
      - uses: actions-rs/cargo@v1
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
        with:
          command: test
          args: --features=paid-tests,long-tests --workspace --all-targets

  test-stable:
    name: Test Stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
        with:
          command: test
          args: --features=paid-tests,long-tests --workspace --all-targets
